sudo: required
services:
    - docker

before_install:
  - docker build -t khalidshaheen/docker-react -f Dockerfile.dev .

script:
  - docker run khalidshaheen/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstock
  region: "us-east-2"
  app: "docker-react"
  env: " DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-718925262378"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"